name: Deploy to EC2 (Apache)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to EC2 Server
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "
          cd /var/www/html && \
          sudo git pull origin main && \
          sudo chown -R www-data:www-data /var/www/html && \
          sudo systemctl restart apache2
        "
